name: 'comment-hider'
description: 'Github Action to hide Bot comments'
branding:
  color: gray-dark
  icon: check
author: 'kanga333'
inputs:
  github_token:
    description: 'The GitHub token used to create an authenticated client'
    required: true
  hide_user_name:
    description: 'Github username to hide comments'
    default: 'github-actions[bot]'
    required: false
  hide_reason:
    description: 'Reasons to hide comments'
    default: 'OUTDATED'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
