on:
  workflow_run:
    workflows:
      - Create artifact
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  my_comment_job:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            const [matchArtifact] = artifacts.data.artifacts.filter(a => a.name == "message");
            const download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: "zip",
            });
            fs.writeFileSync("hello.zip", Buffer.from(download.data));

      - run: unzip hello.zip

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            await github.issues.createComment({
              issue_number: fs.readFileSync("pr_number.txt", { encoding: "utf8" }),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fs.readFileSync("message.txt"),
            })

      - id: pr-number
        run: echo "::set-output name=prNumber::$(cat pr_number.txt)"

      - uses: Akuli/comment-hider@number-arg
        name: Hide old comments
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ steps.pr-number.outputs.prNumber }}
